import {
  Droplet,
  Cross,
  Leaf,
  Apple,
  Popsicle,
  Beer,
  GlassWater,
  Grape,
  Dessert,
  Cake,
  Wine,
} from "lucide-react";

export type Product = {
  category: "panaky" | "pivo" | "drinky" | "jidlo";
  name: string;
  fullName: string;
  price: number;
  amount: string;

  // React icon component OR asset image path
  icon?: React.ElementType;
  image?: string;

  description?: string;
  primaryColor: string;
  bgColor: string;
  borderColor: string;
};

export const products: Product[] = [
  // panaky / shots
  {
    category: "panaky",
    name: "Jäger",
    fullName: "Jägermeister",
    price: 40,
    amount: "0,02 l",
    image: "/images/products/jager.png",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Jäger",
    fullName: "Jägermeister",
    price: 60,
    amount: "0,04 l",
    image: "/images/products/jager.png",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Zelená",
    fullName: "Zelená",
    price: 30,
    amount: "0,02 l",
    icon: Leaf,
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Zelená",
    fullName: "Zelená",
    price: 50,
    amount: "0,04 l",
    icon: Leaf,
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Lemond",
    fullName: "Becherovka Lemond",
    price: 30,
    amount: "0,02 l",
    image: "/images/products/lemond.jpg",
    primaryColor: "text-green-700",
    bgColor: "bg-yellow-100",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Lemond",
    fullName: "Becherovka Lemond",
    price: 50,
    amount: "0,04 l",
    image: "/images/products/lemond.jpg",
    primaryColor: "text-green-700",
    bgColor: "bg-yellow-100",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Jack Daniels",
    fullName: "Jack Daniels (Honey/Fire)",
    price: 40,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/jackdaniels.png",
    primaryColor: "text-white",
    bgColor: "bg-orange-700",
    borderColor: "border-orange-900",
  },
  {
    category: "panaky",
    name: "Jack Daniels",
    fullName: "Jack Daniels (Honey/Fire)",
    price: 60,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/jackdaniels.png",
    primaryColor: "text-white",
    bgColor: "bg-orange-700",
    borderColor: "border-orange-900",
  },
  {
    category: "panaky",
    name: "Morgan",
    fullName: "Captain Morgan",
    price: 40,
    amount: "0,02 l",
    image: "/images/products/morgan.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-600",
    borderColor: "border-yellow-400",
  },
  {
    category: "panaky",
    name: "Morgan",
    fullName: "Captain Morgan",
    price: 60,
    amount: "0,04 l",
    image: "/images/products/morgan.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-600",
    borderColor: "border-yellow-400",
  },
  {
    category: "panaky",
    name: "Vodka",
    fullName: "Vodka",
    price: 30,
    amount: "0,02 l",
    icon: Droplet,
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Vodka",
    fullName: "Vodka",
    price: 50,
    amount: "0,04 l",
    icon: Droplet,
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Republica",
    fullName: "Rum Republica",
    price: 30,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/republica.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-black-900",
  },
  {
    category: "panaky",
    name: "Republica",
    fullName: "Rum Republica",
    price: 50,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/republica.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-black-900",
  },
  {
    category: "panaky",
    name: "Božkov káva",
    fullName: "Rum Božkov kávový",
    price: 30,
    amount: "0,02 l",
    image: "/images/products/bozkovKava.webp",
    primaryColor: "text-white",
    bgColor: "bg-yellow-700/70",
    borderColor: "border-yellow-800",
  },
  {
    category: "panaky",
    name: "Božkov káva",
    fullName: "Rum Božkov kávový",
    price: 50,
    amount: "0,04 l",
    image: "/images/products/bozkovKava.webp",
    primaryColor: "text-white",
    bgColor: "bg-yellow-700/70",
    borderColor: "border-yellow-800",
  },

  {
    category: "panaky",
    name: "Jelzin (Jabko)",
    fullName: "Jelzin Jablko",
    price: 30,
    amount: "0,02 l",
    icon: Apple,
    primaryColor: "text-lime-700",
    bgColor: "bg-green-50",
    borderColor: "border-lime-700",
  },
  {
    category: "panaky",
    name: "Jelzin (Jabko)",
    fullName: "Jelzin Jablko",
    price: 50,
    amount: "0,04 l",
    icon: Apple,
    primaryColor: "text-lime-700",
    bgColor: "bg-green-50",
    borderColor: "border-lime-700",
  },
  {
    category: "panaky",
    name: "Befeeter",
    fullName: "Befeeter pink Gin",
    price: 30,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/befeeter.png",
    primaryColor: "text-pink-700",
    bgColor: "bg-pink-200",
    borderColor: "border-pink-700",
  },
  {
    category: "panaky",
    name: "Befeeter",
    fullName: "Befeeter pink Gin",
    price: 50,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/befeeter.png",
    primaryColor: "text-pink-700",
    bgColor: "bg-pink-200",
    borderColor: "border-pink-700",
  },
  {
    category: "panaky",
    name: "Polar",
    fullName: "Polar - jahoda",
    price: 30,
    amount: "0,02 l",
    icon: Popsicle,
    primaryColor: "text-white",
    bgColor: "bg-red-700",
    borderColor: "border-red-900",
  },
  {
    category: "panaky",
    name: "Polar",
    fullName: "Polar - jahoda",
    price: 50,
    amount: "0,04 l",
    icon: Popsicle,
    primaryColor: "text-white",
    bgColor: "bg-red-700",
    borderColor: "border-red-900",
  },

  // pivo / beer
  {
    category: "pivo",
    name: "Záloha (vrácení)",
    fullName: "Záloha za kelímek (vrácení)",
    price: -50,
    amount: "-1 ks",
    icon: GlassWater,
    primaryColor: "text-red-500",
    bgColor: "bg-red-50",
    borderColor: "border-red-500",
  },
  {
    category: "pivo",
    name: "Záloha",
    fullName: "Záloha za kelímek",
    price: 50,
    amount: "1 ks",
    icon: GlassWater,
    primaryColor: "text-gray-500",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-500",
  },
  {
    category: "pivo",
    name: "Birell nealko",
    fullName: "Birell nealko",
    price: 40,
    amount: "0,5 l",
    image: "/images/products/birell.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-amber-600",
  },
  {
    category: "pivo",
    name: "Pivo",
    fullName: "Pivo",
    price: 50,
    amount: "0,5 l",
    icon: Beer,
    primaryColor: "text-black-600",
    bgColor: "bg-amber-200",
    borderColor: "border-amber-600",
  },
  {
    category: "pivo",
    name: "Cider",
    fullName: "Cider",
    price: 30,
    amount: "0,3 l",
    image: "/images/products/cider.png",
    primaryColor: "text-amber-900",
    bgColor: "bg-orange-400",
    borderColor: "border-amber-800",
  },
  {
    category: "pivo",
    name: "Cider",
    fullName: "Cider",
    price: 50,
    amount: "0,5 l",
    image: "/images/products/cider.png",
    primaryColor: "text-amber-900",
    bgColor: "bg-orange-400",
    borderColor: "border-amber-800",
  },
  {
    category: "pivo",
    name: "Malina",
    fullName: "Limo Malina",
    price: 25,
    amount: "0,3 l",
    icon: Grape,
    primaryColor: "text-red-700",
    bgColor: "bg-red-200",
    borderColor: "border-red-700",
  },
  {
    category: "pivo",
    name: "Malina",
    fullName: "Limo Malina",
    price: 40,
    amount: "0,5 l",
    icon: Grape,
    primaryColor: "text-red-700",
    bgColor: "bg-red-200",
    borderColor: "border-red-700",
  },
  {
    category: "pivo",
    name: "Cola",
    fullName: "Cola",
    price: 40,
    amount: "0,3 l",
    image: "/images/products/cola.png",
    primaryColor: "text-black",
    bgColor: "bg-red-600",
    borderColor: "border-black",
  },
  {
    category: "pivo",
    name: "Džus",
    fullName: "Džus",
    price: 40,
    amount: "0,3 l",
    image: "/images/products/juice.png",
    primaryColor: "text-orange-800",
    bgColor: "bg-orange-200",
    borderColor: "border-orange-900",
  },
  {
    category: "pivo",
    name: "Jem.per.voda",
    fullName: "Jemně perlivá voda",
    price: 10,
    amount: "0,3 l",
    icon: Droplet,
    primaryColor: "text-sky-800",
    bgColor: "bg-cyan-100",
    borderColor: "border-cyan-300",
  },
  {
    category: "pivo",
    name: "Jem.per.voda",
    fullName: "Jemně perlivá voda",
    price: 20,
    amount: "0,5 l",
    icon: Droplet,
    primaryColor: "text-sky-800",
    bgColor: "bg-cyan-100",
    borderColor: "border-cyan-300",
  },

  // drinky / drinks
  {
    category: "drinky",
    name: "Záloha (vrácení)",
    fullName: "Záloha za kelímek (vrácení)",
    price: -50,
    amount: "-1 ks",
    icon: GlassWater,
    primaryColor: "text-red-500",
    bgColor: "bg-red-50",
    borderColor: "border-red-500",
  },
  {
    category: "drinky",
    name: "Záloha",
    fullName: "Záloha za kelímek",
    price: 50,
    amount: "1 ks",
    icon: GlassWater,
    primaryColor: "text-gray-500",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-500",
  },
  {
    category: "drinky",
    name: "Gin+Tonic",
    fullName: "Gin+Tonic",
    price: 90,
    amount: "0,3 l",
    image: "/images/products/befeeter.png",
    primaryColor: "text-pink-700",
    bgColor: "bg-pink-200",
    borderColor: "border-pink-700",
  },
  {
    category: "drinky",
    name: "Cola+Morgen",
    fullName: "Cola+Morgen",
    price: 100,
    amount: "0,3 l",
    image: "/images/products/morgan.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-600",
    borderColor: "border-black-900",
  },
  {
    category: "drinky",
    name: "Cola+Republica",
    fullName: "Cola+Republica",
    price: 90,
    amount: "0,3 l",
    image: "/images/products/republica.png",
    primaryColor: "text-amber-600",
    bgColor: "bg-black",
    borderColor: "border-amber-700",
  },
  {
    category: "drinky",
    name: "Redbull+Vodka",
    fullName: "Redbull+Vodka",
    price: 100,
    amount: "0,3 l",
    icon: Droplet,
    primaryColor: "text-white",
    bgColor: "bg-blue-700",
    borderColor: "border-red-700",
  },
  {
    category: "drinky",
    name: "Džus+Vodka",
    fullName: "Džus+Vodka",
    price: 90,
    amount: "0,3 l",
    icon: Droplet,
    primaryColor: "text-white",
    bgColor: "bg-orange-400",
    borderColor: "border-orange-900",
  },
  {
    category: "drinky",
    name: "Cola",
    fullName: "Cola",
    price: 40,
    amount: "0,3 l",
    image: "/images/products/cola.png",
    primaryColor: "text-black",
    bgColor: "bg-red-600",
    borderColor: "border-black",
  },
  {
    category: "drinky",
    name: "Džus",
    fullName: "Džus",
    price: 40,
    amount: "0,3 l",
    image: "/images/products/juice.png",
    primaryColor: "text-orange-800",
    bgColor: "bg-orange-200",
    borderColor: "border-orange-900",
  },
  {
    category: "drinky",
    name: "Redbull",
    fullName: "Redbull",
    price: 50,
    amount: "0,3 l",
    icon: Droplet,
    primaryColor: "text-yellow-300",
    bgColor: "bg-blue-900",
    borderColor: "border-red-600",
  },
  {
    category: "drinky",
    name: "Jem.per.voda",
    fullName: "Jemně perlivá voda",
    price: 10,
    amount: "0,3 l",
    icon: Droplet,
    primaryColor: "text-sky-800",
    bgColor: "bg-cyan-100",
    borderColor: "border-cyan-300",
  },
  {
    category: "drinky",
    name: "Jem.per.voda",
    fullName: "Jemně perlivá voda",
    price: 20,
    amount: "0,5 l",
    icon: Droplet,
    primaryColor: "text-sky-800",
    bgColor: "bg-cyan-100",
    borderColor: "border-cyan-300",
  },
  {
    category: "drinky",
    name: "Víno b./č. - v. střik",
    fullName: "Víno bílé/červené - Vinný střik",
    price: 60,
    amount: "0,3 l - 0.5l",
    icon: Wine,
    primaryColor: "text-white",
    bgColor: "bg-red-900",
    borderColor: "border-amber-300",
  },

  // jidlo / food
  {
    category: "jidlo",
    name: "Párek v rohlíku",
    fullName: "Párek v rohlíku",
    price: 40,
    amount: "1ks",
    image: "/images/products/parek.jpg",
    primaryColor: "text-orange-700",
    bgColor: "bg-orange-50",
    borderColor: "border-red-700",
  },
  {
    category: "jidlo",
    name: "Langoš",
    fullName: "Langoš",
    price: 100,
    amount: "1ks",
    icon: Dessert,
    primaryColor: "text-orange-900",
    bgColor: "bg-orange-300",
    borderColor: "border-red-700",
  },
  {
    category: "jidlo",
    name: "Deserty",
    fullName: "Deserty",
    price: 50,
    amount: "-",
    icon: Cake,
    primaryColor: "text-pink-800",
    bgColor: "bg-pink-200",
    borderColor: "border-pink-700",
  },
  {
    category: "jidlo",
    name: "Káva",
    fullName: "Káva (turek/rozpustná)",
    price: 25,
    amount: "1ks",
    image: "/images/products/bozkovKava.webp",
    primaryColor: "text-white",
    bgColor: "bg-yellow-700/70",
    borderColor: "border-yellow-800",
  },
  {
    category: "jidlo",
    name: "Víno b./č. - v. střik",
    fullName: "Vinný střik",
    price: 60,
    amount: "0.5l",
    icon: Wine,
    primaryColor: "text-black",
    bgColor: "bg-yellow-100",
    borderColor: "border-amber-300",
  },
];
