import {
  Droplet,
  Cross,
  Leaf,
  Apple,
  Popsicle,
  Beer,
  GlassWater,
} from "lucide-react";

export type Product = {
  category: "panaky" | "pivo" | "drinky" | "jidlo";
  name: string;
  fullName: string;
  price: number;
  amount: string;

  // React icon component OR asset image path
  icon?: React.ElementType;
  image?: string;

  description?: string;
  primaryColor: string;
  bgColor: string;
  borderColor: string;
};

export const products: Product[] = [
  // panaky / shots
  {
    category: "panaky",
    name: "Jäger",
    fullName: "Jägermeister",
    price: 40,
    amount: "0,02 l",
    image: "/images/products/jager.png",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Jäger",
    fullName: "Jägermeister",
    price: 60,
    amount: "0,04 l",
    image: "/images/products/jager.png",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Zelená",
    fullName: "Zelená",
    price: 25,
    amount: "0,02 l",
    icon: Leaf,
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Zelená",
    fullName: "Zelená",
    price: 50,
    amount: "0,04 l",
    icon: Leaf,
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Lemond",
    fullName: "Becherovka Lemond",
    price: 30,
    amount: "0,02 l",
    image: "/images/products/lemond.jpg",
    primaryColor: "text-green-700",
    bgColor: "bg-yellow-100",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Lemond",
    fullName: "Becherovka Lemond",
    price: 50,
    amount: "0,04 l",
    image: "/images/products/lemond.jpg",
    primaryColor: "text-green-700",
    bgColor: "bg-yellow-100",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Jack Daniels",
    fullName: "Jack Daniels (Honey/Fire)",
    price: 40,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/jackdaniels.png",
    primaryColor: "text-white",
    bgColor: "bg-orange-700",
    borderColor: "border-orange-900",
  },
  {
    category: "panaky",
    name: "Jack Daniels",
    fullName: "Jack Daniels (Honey/Fire)",
    price: 60,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/jackdaniels.png",
    primaryColor: "text-white",
    bgColor: "bg-orange-700",
    borderColor: "border-orange-900",
  },
  {
    category: "panaky",
    name: "Morgan",
    fullName: "Captain Morgan",
    price: 40,
    amount: "0,02 l",
    image: "/images/products/morgan.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-600",
    borderColor: "border-yellow-400",
  },
  {
    category: "panaky",
    name: "Morgan",
    fullName: "Captain Morgan",
    price: 60,
    amount: "0,04 l",
    image: "/images/products/morgan.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-600",
    borderColor: "border-yellow-400",
  },
  {
    category: "panaky",
    name: "Vodka",
    fullName: "Vodka",
    price: 30,
    amount: "0,02 l",
    icon: Droplet,
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Vodka",
    fullName: "Vodka",
    price: 50,
    amount: "0,04 l",
    icon: Droplet,
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Republica",
    fullName: "Rum Republica",
    price: 30,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/republica.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-black-900",
  },
  {
    category: "panaky",
    name: "Republica",
    fullName: "Rum Republica",
    price: 50,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/republica.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-black-900",
  },
  {
    category: "panaky",
    name: "Božkov káva",
    fullName: "Rum Božkov kávový",
    price: 30,
    amount: "0,02 l",
    image: "/images/products/bozkovKava.webp",
    primaryColor: "text-white",
    bgColor: "bg-yellow-700/70",
    borderColor: "border-yellow-800",
  },
  {
    category: "panaky",
    name: "Božkov káva",
    fullName: "Rum Božkov kávový",
    price: 50,
    amount: "0,04 l",
    image: "/images/products/bozkovKava.webp",
    primaryColor: "text-white",
    bgColor: "bg-yellow-700/70",
    borderColor: "border-yellow-800",
  },

  {
    category: "panaky",
    name: "Jelzin (Jabko)",
    fullName: "Jelzin Jablko",
    price: 30,
    amount: "0,02 l",
    icon: Apple,
    primaryColor: "text-lime-700",
    bgColor: "bg-green-50",
    borderColor: "border-lime-700",
  },
  {
    category: "panaky",
    name: "Jelzin (Jabko)",
    fullName: "Jelzin Jablko",
    price: 50,
    amount: "0,04 l",
    icon: Apple,
    primaryColor: "text-lime-700",
    bgColor: "bg-green-50",
    borderColor: "border-lime-700",
  },
  {
    category: "panaky",
    name: "Befeeter",
    fullName: "Befeeter pink Gin",
    price: 30,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/befeeter.png",
    primaryColor: "text-pink-700",
    bgColor: "bg-pink-200",
    borderColor: "border-pink-700",
  },
  {
    category: "panaky",
    name: "Befeeter",
    fullName: "Befeeter pink Gin",
    price: 50,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/befeeter.png",
    primaryColor: "text-pink-700",
    bgColor: "bg-pink-200",
    borderColor: "border-pink-700",
  },
  {
    category: "panaky",
    name: "Polar",
    fullName: "Polar - jahoda",
    price: 30,
    amount: "0,02 l",
    icon: Popsicle,
    primaryColor: "text-white",
    bgColor: "bg-red-700",
    borderColor: "border-red-900",
  },
  {
    category: "panaky",
    name: "Polar",
    fullName: "Polar - jahoda",
    price: 50,
    amount: "0,04 l",
    icon: Popsicle,
    primaryColor: "text-white",
    bgColor: "bg-red-700",
    borderColor: "border-red-900",
  },

  // pivo / beer
  {
    category: "pivo",
    name: "Záloha",
    fullName: "Záloha za kelímek",
    price: 50,
    amount: "1 ks",
    icon: GlassWater,
    primaryColor: "text-gray-500",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-500",
  },
  {
    category: "pivo",
    name: "Pivo",
    fullName: "Pivo",
    price: 50,
    amount: "0,5 l",
    icon: Beer,
    primaryColor: "text-black-600",
    bgColor: "bg-amber-200",
    borderColor: "border-amber-600",
  },

  // drinky / drinks
  {
    category: "drinky",
    name: "Záloha",
    fullName: "Záloha za kelímek",
    price: 50,
    amount: "1 ks",
    icon: GlassWater,
    primaryColor: "text-gray-500",
    bgColor: "bg-gray-50",
    borderColor: "border-gray-500",
  },
  {
    category: "drinky",
    name: "Cola+Morgen",
    fullName: "Cola+Morgen",
    price: 100,
    amount: "0,3 l",
    image: "/images/products/morgan.png",
    primaryColor: "text-white",
    bgColor: "bg-amber-600",
    borderColor: "border-black-900",
  },
  // jidlo / food
  {
    category: "jidlo",
    name: "Párek v rohlíku",
    fullName: "Párek v rohlíku",
    price: 40,
    amount: "1ks",
    image: "/images/products/parek.jpg",
    primaryColor: "text-orange-700",
    bgColor: "bg-orange-50",
    borderColor: "border-red-700",
  },
];
