import { BottleWine, Droplet, Cross, Leaf, ShipWheel } from "lucide-react";

export type Product = {
  category: "panaky" | "pivo" | "drinky" | "jidlo";
  name: string;
  price: number;
  amount: string;

  // React icon component OR asset image path
  icon?: React.ElementType;
  image?: string;

  description?: string;
  primaryColor: string;
  bgColor: string;
  borderColor: string;
};

export const products: Product[] = [
  // panaky / shots
  {
    category: "panaky",
    name: "Jäger",
    price: 40,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/jager.png",
    description: "Bylinný likér Jägermeister, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Jäger",
    price: 70,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/jager.png",
    description: "Bylinný likér Jägermeister, velký panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Vodka",
    price: 40,
    amount: "0,02 l",
    icon: Droplet,
    description: "Vodka, malý panák.",
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Vodka",
    price: 70,
    amount: "0,04 l",
    icon: Droplet,
    description: "Vodka, velký panák.",
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Zelená",
    price: 25,
    amount: "0,02 l",
    icon: Leaf,
    description: "Zelená, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Zelená",
    price: 50,
    amount: "0,04 l",
    icon: Leaf,
    description: "Zelená, velký panák.",
    primaryColor: "text-lime-600",
    bgColor: "bg-lime-50",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Rum",
    price: 40,
    amount: "0,02 l",
    icon: ShipWheel,
    description: "Rum, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-amber-900",
  },
  {
    category: "panaky",
    name: "Rum",
    price: 70,
    amount: "0,04 l",
    icon: ShipWheel,
    description: "Rum, velký panák.",
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },

  // pivo / beer
  {
    category: "pivo",
    name: "Pivo",
    price: 40,
    amount: "0,3 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "pivo",
    name: "Pivo",
    price: 70,
    amount: "0,5 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Jäger",
    price: 40,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/jager.png",
    description: "Bylinný likér Jägermeister, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Jäger",
    price: 70,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/jager.png",
    description: "Bylinný likér Jägermeister, velký panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Vodka",
    price: 40,
    amount: "0,02 l",
    icon: Droplet,
    description: "Vodka, malý panák.",
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Vodka",
    price: 70,
    amount: "0,04 l",
    icon: Droplet,
    description: "Vodka, velký panák.",
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Zelená",
    price: 25,
    amount: "0,02 l",
    icon: Leaf,
    description: "Zelená, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Zelená",
    price: 50,
    amount: "0,04 l",
    icon: Leaf,
    description: "Zelená, velký panák.",
    primaryColor: "text-lime-600",
    bgColor: "bg-lime-50",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Rum",
    price: 40,
    amount: "0,02 l",
    icon: ShipWheel,
    description: "Rum, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-amber-900",
  },
  {
    category: "panaky",
    name: "Rum",
    price: 70,
    amount: "0,04 l",
    icon: ShipWheel,
    description: "Rum, velký panák.",
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },

  // pivo / beer
  {
    category: "pivo",
    name: "Pivo",
    price: 40,
    amount: "0,3 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "pivo",
    name: "Pivo",
    price: 70,
    amount: "0,5 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Jäger",
    price: 40,
    amount: "0,02 l",
    icon: Cross,
    image: "/images/products/jager.png",
    description: "Bylinný likér Jägermeister, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Jäger",
    price: 70,
    amount: "0,04 l",
    icon: Cross,
    image: "/images/products/jager.png",
    description: "Bylinný likér Jägermeister, velký panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-900",
    borderColor: "border-orange-600",
  },
  {
    category: "panaky",
    name: "Vodka",
    price: 40,
    amount: "0,02 l",
    icon: Droplet,
    description: "Vodka, malý panák.",
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Vodka",
    price: 70,
    amount: "0,04 l",
    icon: Droplet,
    description: "Vodka, velký panák.",
    primaryColor: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-700",
  },
  {
    category: "panaky",
    name: "Zelená",
    price: 25,
    amount: "0,02 l",
    icon: Leaf,
    description: "Zelená, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-green-700",
    borderColor: "border-green-900",
  },
  {
    category: "panaky",
    name: "Zelená",
    price: 50,
    amount: "0,04 l",
    icon: Leaf,
    description: "Zelená, velký panák.",
    primaryColor: "text-lime-600",
    bgColor: "bg-lime-50",
    borderColor: "border-green-700",
  },
  {
    category: "panaky",
    name: "Rum",
    price: 40,
    amount: "0,02 l",
    icon: ShipWheel,
    description: "Rum, malý panák.",
    primaryColor: "text-white",
    bgColor: "bg-amber-700",
    borderColor: "border-amber-900",
  },
  {
    category: "panaky",
    name: "Rum",
    price: 70,
    amount: "0,04 l",
    icon: ShipWheel,
    description: "Rum, velký panák.",
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },

  // pivo / beer
  {
    category: "pivo",
    name: "Pivo",
    price: 40,
    amount: "0,3 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "pivo",
    name: "Pivo",
    price: 70,
    amount: "0,5 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },

  // drinky / drinks
  {
    category: "drinky",
    name: "Cola+Morgen",
    price: 100,
    amount: "0,3 l",
    image: "/images/products/morgan.png",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "drinky",
    name: "Cola+Republika",
    price: 100,
    amount: "0,3 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  {
    category: "drinky",
    name: "Redbull + Vodka",
    price: 100,
    amount: "0,3 l",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
  // jidlo / food
  {
    category: "jidlo",
    name: "Párek v rohlíku",
    price: 40,
    amount: "1ks",
    icon: ShipWheel,
    primaryColor: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-green-700",
  },
];
